### ISSUE TITLE
Errors when re-attaching to screen session

### ISSUE THREAD

**Issue by bounceme** [marijnh/tern_for_vim#112]
```
Error detected while processing function SuperTabCodeComplete..tern#Complete:
line    3:
Traceback (most recent call last):
Error detected while processing function SuperTabCodeComplete..tern#Complete:
line    3:
  File "<string>", line 1, in <module>
Error detected while processing function SuperTabCodeComplete..tern#Complete:
line    3:
  File "/Users/mac/.vim/bundle/tern_for_vim/script/tern.py", line 265, in tern_ensureCompletionCached
Error detected while processing function SuperTabCodeComplete..tern#Complete:
line    3:
    {"line": curRow - 1, "ch": curCol})
Error detected while processing function SuperTabCodeComplete..tern#Complete:
line    3:
  File "/Users/mac/.vim/bundle/tern_for_vim/script/tern.py", line 219, in tern_runCommand
Error detected while processing function SuperTabCodeComplete..tern#Complete:
line    3:
    tern_displayError(e + str(silent))
Error detected while processing function SuperTabCodeComplete..tern#Complete:
line    3:
TypeError: unsupported operand type(s) for +: 'URLError' and 'str'
```
I'm using supertab which just invokes the omni completion, though after reattaching these errors are shown.

**Comment by marijnh** [comment]
Attached patch should help (though unfortunately, this error was raised while trying to report another error -- the other one might surface next)

**Comment by bounceme** [comment]
Thank you!
