### ISSUE TITLE
Error: No compatible version found: typescript@'^1.0.1'

### ISSUE THREAD

**Issue by tupton** [marijnh/tern_for_vim#86]
Installing fails due to an incompatible typescript version.

To reproduce:

```
$ cd .../path/to/vim/bundle/tern_for_vim
$ npm install
npm http GET http://registry.npmjs.org/tern
npm http 304 http://registry.npmjs.org/tern
npm http GET http://registry.npmjs.org/acorn
npm http GET http://registry.npmjs.org/glob
npm http GET http://registry.npmjs.org/minimatch
npm http GET http://registry.npmjs.org/typescript
npm http 304 http://registry.npmjs.org/acorn
npm http 304 http://registry.npmjs.org/glob
npm http 304 http://registry.npmjs.org/minimatch
npm http 304 http://registry.npmjs.org/typescript
npm ERR! error installing tern@0.8.0
npm http GET http://registry.npmjs.org/acorn/-/acorn-0.11.0.tgz

npm ERR! Error: No compatible version found: typescript@'^1.0.1'
npm ERR! Valid install targets:
npm ERR! ["0.8.0"]
npm ERR!     at installTargetsError (/usr/share/npm/lib/cache.js:488:10)
npm ERR!     at /usr/share/npm/lib/cache.js:375:15
npm ERR!     at saved (/usr/share/npm/lib/utils/npm-registry-client/get.js:147:7)
npm ERR!     at Object.oncomplete (/usr/lib/nodejs/graceful-fs.js:230:7)
npm ERR! You may report this log at:
npm ERR!     <http://bugs.debian.org/npm>
npm ERR! or use
npm ERR!     reportbug --attach ./npm-debug.log npm
npm ERR!
npm ERR! System Linux 3.2.0-57-virtual
npm ERR! command "node" "/usr/bin/npm" "install"
npm ERR! cwd ./tern_for_vim
npm ERR! node -v v0.6.12
npm ERR! npm -v 1.1.4
npm ERR! message No compatible version found: typescript@'^1.0.1'
npm ERR! message Valid install targets:
npm ERR! message ["0.8.0"]
npm http 200 http://registry.npmjs.org/acorn/-/acorn-0.11.0.tgz
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     ./npm-debug.log
npm not ok
```

**Comment by tupton** [comment]
It *probably* isn't relevant, but this was after setting a non-ssl registry using `npm config set registry http://registry.npmjs.org/`.

**Comment by tupton** [comment]
Also, I realize that this might be an issue with tern itself, not the vim plugin, but that's where I saw this issue. I can move this issue to the tern repository if desired.

**Comment by marijnh** [comment]
For me, running `npm install` in the `tern_for_vim` directory works just fine. Maybe try clearing your npm cache (or upgrading if your npm is old -- I had weirdness like this when using an old npm once).

**Comment by tupton** [comment]
Oh I bet it's an old version of npm. I was trying to install this on an older Ubuntu 12.04 machine.

```
❯ npm --version
1.1.4
```

Locally, I have version 2.1.17. I'll try to get a newer version of npm and retry. Thanks for looking into this.

**Comment by tupton** [comment]
Installing on an Ubuntu 14.04 machine where the npm package version is 1.3.10 works just fine. Thanks for taking a look and sorry for the false alarm. Hopefully this helps anyone else who runs into this issue with an older version of npm.
